# -*- coding: utf-8 -*-
"""Pascalgonic Adjacent-Layer Compactness Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgvMUyk_e7YwcMFGZNnO-DUlLtKCUL0I
"""

# ============================================================
# INTERACTIVE EXPLANATORY FIGURE FOR ADJACENT LAYERS
# Pascalgonic compactness explanation
# ------------------------------------------------------------
# Features:
# 1. Interactive choice of prime p
# 2. Interactive choice of adjacent layers (R_k, R_{k+1})
# 3. theta_1 starts at 90 degrees consistently for singleton bits
# 4. Sharper text / higher-quality export for article use
# 5. Layer selection is safely capped by: [1, p-1]
# ============================================================

import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Wedge, Circle
from scipy.optimize import linear_sum_assignment
import ipywidgets as widgets
from IPython.display import display, clear_output


# ============================================================
# GLOBAL STYLE
# ============================================================

plt.rcParams.update({
    "font.size": 11,
    "axes.titlesize": 13,
    "figure.dpi": 180,
    "savefig.dpi": 600,
    "mathtext.fontset": "dejavuserif",
    "font.family": "serif",
    "text.antialiased": True,
    "lines.antialiased": True,
    "patch.antialiased": True,
    "lines.solid_capstyle": "round",
    "lines.solid_joinstyle": "round",
})


# ============================================================
# BASIC UTILITIES
# ============================================================

def is_prime(n: int) -> bool:
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0:
        return False
    r = int(math.isqrt(n))
    for i in range(3, r + 1, 2):
        if n % i == 0:
            return False
    return True


def popcount(x: int) -> int:
    return bin(x).count("1")


def mask_to_binary(mask: int, p: int) -> str:
    return format(mask, f"0{p}b")


def binary_to_mask(binary: str) -> int:
    return int(binary, 2)


def masks_in_layer(p: int, k: int):
    return [m for m in range(2 ** p) if popcount(m) == k]


def normalize_angle(theta: float) -> float:
    return theta % (2 * math.pi)


def circular_angle_distance(a: float, b: float) -> float:
    d = abs(normalize_angle(a - b))
    return min(d, 2 * math.pi - d)


def circular_slot_distance(i: int, j: int, m: int) -> int:
    d = abs(i - j)
    return min(d, m - d)


def pol2cart(r: float, theta: float):
    return r * math.cos(theta), r * math.sin(theta)


def angle_deg(theta: float) -> float:
    return math.degrees(normalize_angle(theta))


def bits_of_mask(mask: int):
    bits = []
    b = 1
    x = mask
    while x:
        if x & 1:
            bits.append(b)
        x >>= 1
        b <<= 1
    return bits


def ha_va_from_angle(theta: float):
    x, y = math.cos(theta), math.sin(theta)

    if x > 0.25:
        ha = "left"
    elif x < -0.25:
        ha = "right"
    else:
        ha = "center"

    if y > 0.25:
        va = "bottom"
    elif y < -0.25:
        va = "top"
    else:
        va = "center"

    return ha, va


def cyclic_offset_from_start(theta: float, start_deg: float) -> float:
    start = np.deg2rad(start_deg)
    return normalize_angle(theta - start)


def layer_cap_formula(p: int) -> int:
    """
    User-requested cap:
        ceil((2^p - 2) / (p - 1))
    """
    if p <= 1:
        return 0
    return math.ceil((2 ** p - 2) / (p - 1))


def max_valid_first_layer(p: int) -> int:
    """
    Adjacent layers are (R_k, R_{k+1}), so the first layer k must satisfy:
        k >= 1
        k <= p - 2
    and also respect the requested cap formula.
    """
    cap_formula = layer_cap_formula(p)
    return max(1, min(p - 2, cap_formula - 1))


def choose_default_target_binary(p: int, k: int) -> str:
    """
    Pick a default target of size k:
        p=5, k=1 -> 00001
        p=5, k=2 -> 00011
        p=5, k=3 -> 00111
    """
    k = max(0, min(k, p))
    return ("0" * (p - k)) + ("1" * k)


# ============================================================
# DIRECTION MODEL
# ============================================================

def build_bit_angles(p: int, rotation_deg: float = 90.0):
    """
    Example for p=5 and rotation_deg=90:
        00001 -> 90°
        00010 -> 162°
        00100 -> 234°
        01000 -> 306°
        10000 -> 18°
    """
    angles = np.linspace(0, 2 * np.pi, p, endpoint=False) + np.deg2rad(rotation_deg)
    return {1 << i: normalize_angle(angles[i]) for i in range(p)}


def mask_direction_angle(mask: int, bit_angles: dict) -> float:
    vx, vy = 0.0, 0.0
    for bit, ang in bit_angles.items():
        if mask & bit:
            vx += math.cos(ang)
            vy += math.sin(ang)

    if abs(vx) < 1e-12 and abs(vy) < 1e-12:
        return 0.0

    return normalize_angle(math.atan2(vy, vx))


def minor_arc_midpoint(a: float, b: float) -> float:
    a = normalize_angle(a)
    b = normalize_angle(b)
    diff = (b - a) % (2 * math.pi)

    if diff <= math.pi:
        return normalize_angle(a + 0.5 * diff)

    return normalize_angle(b + 0.5 * ((a - b) % (2 * math.pi)))


def visual_angle_for_mask(mask: int, bit_angles: dict) -> float:
    """
    Visual angle for explanatory panel:
    - singleton in R1: bit direction
    - 2-element subset in R2: midpoint between two singleton directions
    - higher layers: vector-sum direction
    """
    bits = bits_of_mask(mask)

    if len(bits) == 1:
        return bit_angles[bits[0]]

    if len(bits) == 2:
        a1 = bit_angles[bits[0]]
        a2 = bit_angles[bits[1]]
        return minor_arc_midpoint(a1, a2)

    return mask_direction_angle(mask, bit_angles)


def initial_ring_order(masks, bit_angles, rotation_deg=90.0):
    return sorted(
        masks,
        key=lambda m: cyclic_offset_from_start(
            mask_direction_angle(m, bit_angles),
            rotation_deg
        )
    )


def build_partition_centers(m: int, rotation_deg: float = 90.0):
    sector_width = 2 * math.pi / m
    start_center = np.deg2rad(rotation_deg)
    return [normalize_angle(start_center + j * sector_width) for j in range(m)]


# ============================================================
# TARGET RELATION
# ============================================================

def is_subset_mask(a: int, b: int) -> bool:
    return (a & b) == a


def is_superset_mask(a: int, b: int) -> bool:
    return (a & b) == b


def proper_subset_mask(a: int, b: int) -> bool:
    return a != b and is_subset_mask(a, b)


def proper_superset_mask(a: int, b: int) -> bool:
    return a != b and is_superset_mask(a, b)


def relation_to_target(mask: int, target_mask: int) -> str:
    if mask == target_mask:
        return "target"
    if proper_subset_mask(mask, target_mask):
        return "proper subset"
    if proper_superset_mask(mask, target_mask):
        return "proper superset"
    return "unrelated"


def is_related(mask: int, target_mask: int) -> bool:
    return relation_to_target(mask, target_mask) != "unrelated"


# ============================================================
# COST + COMPACT BLOCK ASSIGNMENT
# ============================================================

def build_base_cost_matrix(
    ordered_masks,
    partition_centers,
    bit_angles,
    alpha=1.0,
    beta=0.20,
):
    m = len(ordered_masks)
    sector_width = 2 * math.pi / m
    C = np.zeros((m, m), dtype=float)

    for i, mask in enumerate(ordered_masks):
        theta = mask_direction_angle(mask, bit_angles)
        for j, phi in enumerate(partition_centers):
            angular_cost = circular_angle_distance(theta, phi) / sector_width
            displacement_cost = circular_slot_distance(i, j, m)
            C[i, j] = alpha * angular_cost + beta * displacement_cost

    return C


def ordered_cyclic_block_slots(start: int, length: int, m: int):
    return [(start + t) % m for t in range(length)]


def ordered_complement_slots(block_slots, m: int):
    block_set = set(block_slots)
    return [j for j in range(m) if j not in block_set]


def solve_square_assignment(C: np.ndarray):
    row_ind, col_ind = linear_sum_assignment(C)
    objective = C[row_ind, col_ind].sum()
    return {int(r): int(c) for r, c in zip(row_ind, col_ind)}, float(objective)


def compactify_ring_by_block_scipy(
    masks,
    bit_angles,
    target_mask,
    rotation_deg=90.0,
    alpha=1.0,
    beta=0.20,
):
    ordered_masks = initial_ring_order(masks, bit_angles, rotation_deg=rotation_deg)
    m = len(ordered_masks)
    centers = build_partition_centers(m, rotation_deg=rotation_deg)

    base_cost = build_base_cost_matrix(
        ordered_masks=ordered_masks,
        partition_centers=centers,
        bit_angles=bit_angles,
        alpha=alpha,
        beta=beta,
    )

    related_rows = [i for i, mk in enumerate(ordered_masks) if is_related(mk, target_mask)]
    unrelated_rows = [i for i, mk in enumerate(ordered_masks) if not is_related(mk, target_mask)]

    h = len(related_rows)

    if h == 0 or h == m:
        assignment, _ = solve_square_assignment(base_cost)
        assigned_masks = [None] * m
        for r, c in assignment.items():
            assigned_masks[c] = ordered_masks[r]

        return {
            "ordered_masks": ordered_masks,
            "partition_centers": centers,
            "assignment_row_to_col": assignment,
            "assigned_masks_by_partition": assigned_masks,
            "block_slots": list(range(m)) if h == m else [],
            "base_cost_matrix": base_cost,
        }

    best_obj = None
    best_assignment = None
    best_block_slots = None

    for start in range(m):
        block_slots = ordered_cyclic_block_slots(start, h, m)
        other_slots = ordered_complement_slots(block_slots, m)

        C_rel = base_cost[np.ix_(related_rows, block_slots)]
        C_unrel = base_cost[np.ix_(unrelated_rows, other_slots)]

        rel_assignment_local, rel_obj = solve_square_assignment(C_rel)
        unrel_assignment_local, unrel_obj = solve_square_assignment(C_unrel)

        assignment = {}
        for r_local, c_local in rel_assignment_local.items():
            assignment[related_rows[r_local]] = block_slots[c_local]
        for r_local, c_local in unrel_assignment_local.items():
            assignment[unrelated_rows[r_local]] = other_slots[c_local]

        obj = rel_obj + unrel_obj

        if best_obj is None or obj < best_obj:
            best_obj = obj
            best_assignment = assignment
            best_block_slots = block_slots

    assigned_masks = [None] * m
    for r, c in best_assignment.items():
        assigned_masks[c] = ordered_masks[r]

    return {
        "ordered_masks": ordered_masks,
        "partition_centers": centers,
        "assignment_row_to_col": best_assignment,
        "assigned_masks_by_partition": assigned_masks,
        "block_slots": best_block_slots,
        "base_cost_matrix": base_cost,
    }


# ============================================================
# DRAWING HELPERS
# ============================================================

def draw_radial_arrow(ax, theta, r0, r1, color="black", lw=1.5, ls="-", alpha=1.0):
    x0, y0 = pol2cart(r0, theta)
    x1, y1 = pol2cart(r1, theta)
    ax.annotate(
        "",
        xy=(x1, y1),
        xytext=(x0, y0),
        arrowprops=dict(
            arrowstyle="->",
            lw=lw,
            color=color,
            linestyle=ls,
            alpha=alpha,
            shrinkA=0,
            shrinkB=0,
            mutation_scale=10,
        ),
    )


def tangential_rotation_deg(theta_rad: float) -> float:
    rot = angle_deg(theta_rad) - 90.0
    if rot < -90:
        rot += 180
    if rot > 90:
        rot -= 180
    return rot


def font_size_for_sector_count(m: int, base=10):
    if m <= 5:
        return base
    if m <= 8:
        return base - 1
    if m <= 12:
        return base - 2
    return max(6, base - 3)


def draw_ring_partition_lines(
    ax,
    centers,
    r_inner,
    r_outer,
    color="#9a9a9a",
    lw=0.9,
    ls="--",
    alpha=0.8,
):
    for c in centers:
        x0, y0 = pol2cart(r_inner, c)
        x1, y1 = pol2cart(r_outer, c)
        ax.plot([x0, x1], [y0, y1], color=color, lw=lw, ls=ls, alpha=alpha, zorder=3)


def add_polyline_label(ax, text, anchor_xy, mid1_xy, mid2_xy, text_xy, ha="left"):
    xs = [anchor_xy[0], mid1_xy[0], mid2_xy[0], text_xy[0]]
    ys = [anchor_xy[1], mid1_xy[1], mid2_xy[1], text_xy[1]]
    ax.plot(xs, ys, color="#555555", lw=1.0, zorder=18)
    ax.text(
        text_xy[0],
        text_xy[1],
        text,
        ha=ha,
        va="center",
        fontsize=12,
        fontweight="semibold",
        color="#333333",
        zorder=19,
        bbox=dict(
            boxstyle="round,pad=0.12",
            fc="white",
            ec="#d9d9d9",
            lw=0.4,
            alpha=0.96,
        ),
    )


def draw_sector_ring(
    ax,
    centers,
    labels,
    related_flags,
    r_inner,
    r_outer,
    label_mode="horizontal",
    title=None,
):
    m = len(centers)
    sector_width_deg = 360 / m
    sector_width_rad = 2 * math.pi / m
    fs = font_size_for_sector_count(m, base=9.5)

    for j, center in enumerate(centers):
        theta_deg = angle_deg(center)
        theta1 = theta_deg - sector_width_deg / 2
        theta2 = theta_deg + sector_width_deg / 2

        facecolor = "#cfaa45" if related_flags[j] else "#ededed"

        wedge = Wedge(
            (0, 0),
            r_outer,
            theta1,
            theta2,
            width=(r_outer - r_inner),
            facecolor=facecolor,
            edgecolor="#222222",
            linewidth=1.0,
            zorder=1,
        )
        ax.add_patch(wedge)

    draw_ring_partition_lines(ax, centers, r_inner, r_outer)

    for j, center in enumerate(centers):
        rl = r_inner + 0.47 * (r_outer - r_inner)
        if sector_width_rad < 0.75:
            rl = r_inner + 0.44 * (r_outer - r_inner)

        xl, yl = pol2cart(rl, center)
        rotation = 0 if label_mode == "horizontal" else tangential_rotation_deg(center)

        ax.text(
            xl,
            yl,
            labels[j],
            ha="center",
            va="center",
            fontsize=fs,
            rotation=rotation,
            rotation_mode="anchor",
            clip_on=False,
            color="#111111",
            zorder=5,
            bbox=dict(
                boxstyle="round,pad=0.10",
                fc="white",
                ec="#d8d8d8",
                lw=0.35,
                alpha=0.95,
            ),
        )

    if title:
        ax.set_title(title, fontsize=13, pad=12)


def place_subset_theta_labels_general(
    ax,
    masks,
    bit_angles,
    p,
    base_radius,
    bit_fontsize,
    target_mask=None,
    angle_min_sep_deg=14,
    rotation_deg=90.0,
):
    """
    General theta labels for any selected first layer.
    Labels are numbered according to the cyclic order starting from rotation_deg.
    """
    ordered = sorted(
        masks,
        key=lambda mk: cyclic_offset_from_start(
            visual_angle_for_mask(mk, bit_angles),
            rotation_deg
        )
    )
    theta_index_map = {mk: i + 1 for i, mk in enumerate(ordered)}
    items = [(visual_angle_for_mask(mk, bit_angles), mk) for mk in ordered]

    placed_angles_deg = []
    toggle = 0

    for th, mk in items:
        th_deg = angle_deg(th)
        label_r = base_radius

        if placed_angles_deg:
            prev = placed_angles_deg[-1]
            diff = abs(th_deg - prev)
            diff = min(diff, 360 - diff)
            if diff < angle_min_sep_deg:
                label_r += 0.10 if toggle % 2 == 0 else 0.18
                toggle += 1

        x, y = pol2cart(label_r, th)
        color = "#9c7300" if (target_mask is not None and is_related(mk, target_mask)) else "#222222"
        ha, va = ha_va_from_angle(th)

        theta_value = int(round(th_deg))
        theta_idx = theta_index_map[mk]
        label_text = f"{mask_to_binary(mk, p)}\n" + rf"$\theta_{{{theta_idx}}}={theta_value}^\circ$"

        ax.text(
            x,
            y,
            label_text,
            ha=ha,
            va=va,
            fontsize=bit_fontsize,
            fontweight="medium",
            color=color,
            linespacing=1.10,
            bbox=dict(
                boxstyle="round,pad=0.12",
                fc="white",
                ec="#d0d0d0",
                lw=0.4,
                alpha=0.97,
            ),
            zorder=12,
        )
        placed_angles_deg.append(th_deg)


def place_outer_phi_labels(
    ax,
    centers,
    base_radius,
    fontsize=8.8,
    angle_min_sep_deg=12,
    color="#4f4f4f",
    rotation_deg=90.0,
):
    items = [(phi, j) for j, phi in enumerate(centers, start=1)]
    items.sort(key=lambda x: cyclic_offset_from_start(x[0], rotation_deg))

    placed_angles_deg = []
    toggle = 0

    for phi, j in items:
        phi_deg = angle_deg(phi)
        label_r = base_radius

        if placed_angles_deg:
            prev = placed_angles_deg[-1]
            diff = abs(phi_deg - prev)
            diff = min(diff, 360 - diff)
            if diff < angle_min_sep_deg:
                label_r += 0.10 if toggle % 2 == 0 else 0.18
                toggle += 1

        x, y = pol2cart(label_r, phi)
        ha, va = ha_va_from_angle(phi)
        text = rf"$\phi_{{{j}}}={int(round(phi_deg))}^\circ$"

        ax.text(
            x,
            y,
            text,
            ha=ha,
            va=va,
            fontsize=fontsize,
            fontweight="medium",
            color=color,
            bbox=dict(
                boxstyle="round,pad=0.10",
                fc="white",
                ec="#d0d0d0",
                lw=0.35,
                alpha=0.97,
            ),
            zorder=13,
        )
        placed_angles_deg.append(phi_deg)


def draw_guides_between_layers(ax, outer_masks, bit_angles, inner_radius, outer_radius, color="#a3a3a3"):
    """
    Simple visual guide lines from inner ring toward directions of outer ring elements.
    """
    for mk in outer_masks:
        th = visual_angle_for_mask(mk, bit_angles)
        x0, y0 = pol2cart(inner_radius + 0.04, th)
        x1, y1 = pol2cart((inner_radius + outer_radius) / 2.0, th)
        ax.plot([x0, x1], [y0, y1], color=color, lw=0.80, ls=":", alpha=0.95, zorder=2)


# ============================================================
# MAIN GENERAL EXPLANATORY FIGURE
# ============================================================

def plot_adjacent_layers_compactness_explanation(
    p=5,
    layer1=1,
    target_binary=None,
    alpha=1.0,
    beta=0.20,
    rotation_deg=90.0,
    figsize=(16.8, 8.4),
    save_path=None,
    dpi=600,
):
    layer2 = layer1 + 1

    if not is_prime(p):
        raise ValueError(f"p={p} is not prime.")

    if layer1 < 1 or layer2 > p - 1:
        raise ValueError(
            f"Invalid adjacent layers (R_{layer1}, R_{layer2}) for p={p}. "
            f"Allowed first layer is from 1 to {max_valid_first_layer(p)}."
        )

    if target_binary is None:
        target_binary = choose_default_target_binary(p, layer1)

    if len(target_binary) != p or set(target_binary) - {"0", "1"}:
        raise ValueError(f"target_binary must be a binary string of length {p}.")

    target_mask = binary_to_mask(target_binary)
    bit_angles = build_bit_angles(p, rotation_deg=rotation_deg)

    layer1_masks = masks_in_layer(p, layer1)
    layer2_masks = masks_in_layer(p, layer2)

    res1 = compactify_ring_by_block_scipy(
        layer1_masks,
        bit_angles,
        target_mask,
        rotation_deg=rotation_deg,
        alpha=alpha,
        beta=beta,
    )

    res2 = compactify_ring_by_block_scipy(
        layer2_masks,
        bit_angles,
        target_mask,
        rotation_deg=rotation_deg,
        alpha=alpha,
        beta=beta,
    )

    fig, axes = plt.subplots(1, 2, figsize=figsize)
    fig.patch.set_facecolor("white")

    # --------------------------------------------------------
    # PANEL (a): direction geometry
    # --------------------------------------------------------
    ax = axes[0]
    ax.set_aspect("equal")
    ax.axis("off")

    r1_circle = 1.00
    r2_circle = 1.86

    for r, lw in [(r1_circle, 1.1), (r2_circle, 1.1)]:
        ax.add_patch(Circle((0, 0), r, fill=False, ec="#8d8d8d", lw=lw, ls="--", zorder=1))

    for c in res1["partition_centers"]:
        x1, y1 = pol2cart(r1_circle + 0.10, c)
        ax.plot([0, x1], [0, y1], color="#c1c1c1", lw=0.9, ls=":", zorder=1)

    for c in res2["partition_centers"]:
        x1, y1 = pol2cart(r2_circle + 0.11, c)
        ax.plot([0, x1], [0, y1], color="#d8d8d8", lw=0.85, ls=":", zorder=1)

    for mk in res1["ordered_masks"]:
        theta = visual_angle_for_mask(mk, bit_angles)
        color = "#b88700" if is_related(mk, target_mask) else "#222222"
        draw_radial_arrow(ax, theta, 0.0, r1_circle - 0.07, color=color, lw=1.7, alpha=0.98)

    draw_guides_between_layers(ax, res2["ordered_masks"], bit_angles, r1_circle, r2_circle)

    for mk in res2["ordered_masks"]:
        theta = visual_angle_for_mask(mk, bit_angles)
        color = "#b88700" if is_related(mk, target_mask) else "#555555"
        draw_radial_arrow(
            ax,
            theta,
            r1_circle + 0.10,
            r2_circle - 0.10,
            color=color,
            lw=1.35,
            alpha=0.96,
        )

    place_subset_theta_labels_general(
        ax=ax,
        masks=layer1_masks,
        bit_angles=bit_angles,
        p=p,
        base_radius=r1_circle + 0.18,
        bit_fontsize=8.9,
        target_mask=target_mask,
        angle_min_sep_deg=13,
        rotation_deg=rotation_deg,
    )

    place_outer_phi_labels(
        ax=ax,
        centers=res2["partition_centers"],
        base_radius=r2_circle + 0.54,
        fontsize=8.8,
        angle_min_sep_deg=12,
        color="#5b5b5b",
        rotation_deg=rotation_deg,
    )

    add_polyline_label(
        ax=ax,
        text=rf"Layer $R_{layer1}$",
        anchor_xy=pol2cart(r1_circle + 0.02, np.deg2rad(208)),
        mid1_xy=(-1.40, -1.30),
        mid2_xy=(-2.05, -1.30),
        text_xy=(-2.85, -1.30),
        ha="right",
    )

    add_polyline_label(
        ax=ax,
        text=rf"Layer $R_{layer2}$",
        anchor_xy=pol2cart(r2_circle + 0.02, np.deg2rad(28)),
        mid1_xy=(2.00, 1.45),
        mid2_xy=(2.48, 1.45),
        text_xy=(3.06, 1.45),
        ha="left",
    )

    ax.text(
        0,
        0,
        "center",
        ha="center",
        va="center",
        fontsize=9.5,
        color="#333333",
        bbox=dict(boxstyle="round,pad=0.14", fc="white", ec="#d0d0d0", lw=0.4, alpha=0.97),
        zorder=12,
    )

    ax.set_title(
        rf"(a) Direction geometry of $R_{layer1}$ and $R_{layer2}$",
        fontsize=13,
        pad=12,
    )
    ax.set_xlim(-3.45, 3.45)
    ax.set_ylim(-3.05, 3.05)

    # --------------------------------------------------------
    # PANEL (b): compact assignment
    # --------------------------------------------------------
    ax = axes[1]
    ax.set_aspect("equal")
    ax.axis("off")

    labels_r1 = [mask_to_binary(mk, p) for mk in res1["assigned_masks_by_partition"]]
    flags_r1 = [is_related(mk, target_mask) for mk in res1["assigned_masks_by_partition"]]

    draw_sector_ring(
        ax=ax,
        centers=res1["partition_centers"],
        labels=labels_r1,
        related_flags=flags_r1,
        r_inner=0.55,
        r_outer=1.14,
        label_mode="horizontal",
        title=rf"(b) Compact assignment on $R_{layer1}$ and $R_{layer2}$",
    )

    labels_r2 = [mask_to_binary(mk, p) for mk in res2["assigned_masks_by_partition"]]
    flags_r2 = [is_related(mk, target_mask) for mk in res2["assigned_masks_by_partition"]]

    draw_sector_ring(
        ax=ax,
        centers=res2["partition_centers"],
        labels=labels_r2,
        related_flags=flags_r2,
        r_inner=1.38,
        r_outer=2.14,
        label_mode="tangential",
        title=None,
    )

    add_polyline_label(
        ax=ax,
        text=rf"Layer $R_{layer1}$",
        anchor_xy=pol2cart(1.02, np.deg2rad(218)),
        mid1_xy=(-1.38, -1.58),
        mid2_xy=(-2.06, -1.58),
        text_xy=(-2.82, -1.58),
        ha="right",
    )

    add_polyline_label(
        ax=ax,
        text=rf"Layer $R_{layer2}$",
        anchor_xy=pol2cart(2.12, np.deg2rad(32)),
        mid1_xy=(2.00, 1.30),
        mid2_xy=(2.45, 1.30),
        text_xy=(3.00, 1.30),
        ha="left",
    )

    ax.text(
        0,
        -2.52,
        "Gold sectors indicate subsets related to the target region.",
        ha="center",
        fontsize=10.3,
        color="#333333",
    )
    ax.text(
        0,
        -2.75,
        rf"In $R_{layer2}$, the assigned positions of related subsets form one contiguous block.",
        ha="center",
        fontsize=10.3,
        color="#333333",
    )

    ax.set_xlim(-3.28, 3.28)
    ax.set_ylim(-3.02, 2.58)

    plt.tight_layout(pad=1.45)

    if save_path is not None:
        plt.savefig(
            save_path,
            dpi=dpi,
            bbox_inches="tight",
            facecolor="white",
            edgecolor="none",
        )

    plt.show()


# ============================================================
# INTERACTIVE UI
# ============================================================

def build_pascalgonic_adjacent_layers_ui():
    prime_options = [3, 5, 7, 11, 13, 17]
    default_p = 5

    p_dropdown = widgets.Dropdown(
        options=prime_options,
        value=default_p,
        description="Prime p:",
        layout=widgets.Layout(width="220px"),
        style={"description_width": "90px"},
    )

    layer1_dropdown = widgets.Dropdown(
        options=[],
        description="Layer 1:",
        layout=widgets.Layout(width="220px"),
        style={"description_width": "90px"},
    )

    layer2_text = widgets.Text(
        value="R2",
        description="Layer 2:",
        disabled=True,
        layout=widgets.Layout(width="220px"),
        style={"description_width": "90px"},
    )

    target_text = widgets.Text(
        value=choose_default_target_binary(default_p, 1),
        description="Target:",
        layout=widgets.Layout(width="320px"),
        style={"description_width": "90px"},
    )

    alpha_slider = widgets.FloatSlider(
        value=1.0,
        min=0.0,
        max=3.0,
        step=0.05,
        description="Alpha:",
        readout_format=".2f",
        continuous_update=False,
        layout=widgets.Layout(width="360px"),
        style={"description_width": "90px"},
    )

    beta_slider = widgets.FloatSlider(
        value=0.20,
        min=0.0,
        max=1.5,
        step=0.05,
        description="Beta:",
        readout_format=".2f",
        continuous_update=False,
        layout=widgets.Layout(width="360px"),
        style={"description_width": "90px"},
    )

    rotation_slider = widgets.FloatSlider(
        value=90.0,
        min=0.0,
        max=359.0,
        step=1.0,
        description="Rotation:",
        readout_format=".0f",
        continuous_update=False,
        layout=widgets.Layout(width="360px"),
        style={"description_width": "90px"},
    )

    figsize_width = widgets.FloatSlider(
        value=16.8,
        min=10.0,
        max=24.0,
        step=0.2,
        description="Fig width:",
        readout_format=".1f",
        continuous_update=False,
        layout=widgets.Layout(width="360px"),
        style={"description_width": "90px"},
    )

    figsize_height = widgets.FloatSlider(
        value=8.4,
        min=5.0,
        max=14.0,
        step=0.2,
        description="Fig height:",
        readout_format=".1f",
        continuous_update=False,
        layout=widgets.Layout(width="360px"),
        style={"description_width": "90px"},
    )

    dpi_dropdown = widgets.Dropdown(
        options=[300, 400, 600, 800],
        value=600,
        description="DPI:",
        layout=widgets.Layout(width="220px"),
        style={"description_width": "90px"},
    )

    save_path_text = widgets.Text(
        value="",
        placeholder="contoh: adjacent_layers_p5_R1_R2.pdf",
        description="Save path:",
        layout=widgets.Layout(width="520px"),
        style={"description_width": "90px"},
    )

    info_html = widgets.HTML()
    out = widgets.Output()

    render_btn = widgets.Button(
        description="Render Figure",
        button_style="primary",
        icon="picture-o",
        layout=widgets.Layout(width="180px"),
    )

    def update_layer_options(*args):
        p = p_dropdown.value
        kmax = max_valid_first_layer(p)
        options = [(f"R{k}", k) for k in range(1, kmax + 1)]

        if not options:
            options = [("R1", 1)]

        current = layer1_dropdown.value
        layer1_dropdown.options = options
        valid_values = [v for _, v in options]

        if current in valid_values:
            layer1_dropdown.value = current
        else:
            layer1_dropdown.value = valid_values[0]

        k = layer1_dropdown.value
        layer2_text.value = f"R{k+1}"

        default_target = choose_default_target_binary(p, k)
        if len(target_text.value) != p or set(target_text.value) - {"0", "1"}:
            target_text.value = default_target

        formula_cap = layer_cap_formula(p)
        info_html.value = (
            f"<b>Layer cap info</b><br>"
            f"Requested bound: ceil((2^{p} - 2)/({p} - 1)) = <b>{formula_cap}</b><br>"
            f"Usable first-layer choices for adjacent pair (R_k, R_(k+1)): "
            f"<b>1</b> to <b>{kmax}</b>."
        )

    def on_layer1_change(*args):
        k = layer1_dropdown.value
        p = p_dropdown.value
        layer2_text.value = f"R{k+1}"

        if len(target_text.value) != p or set(target_text.value) - {"0", "1"}:
            target_text.value = choose_default_target_binary(p, k)

    def on_render_click(_):
        with out:
            clear_output(wait=True)

            p = p_dropdown.value
            layer1 = layer1_dropdown.value
            layer2 = layer1 + 1
            target_binary = target_text.value.strip()
            alpha = alpha_slider.value
            beta = beta_slider.value
            rotation_deg = rotation_slider.value
            figsize = (figsize_width.value, figsize_height.value)
            dpi = dpi_dropdown.value
            save_path = save_path_text.value.strip() or None

            try:
                if not is_prime(p):
                    raise ValueError("Nilai p harus bilangan prima.")

                if len(target_binary) != p or set(target_binary) - {"0", "1"}:
                    raise ValueError(
                        f"Target harus berupa string biner sepanjang p={p}. "
                        f"Contoh valid: {choose_default_target_binary(p, layer1)}"
                    )

                max_first = max_valid_first_layer(p)
                if layer1 < 1 or layer1 > max_first:
                    raise ValueError(
                        f"Layer pertama harus berada pada rentang 1 sampai {max_first}."
                    )

                plot_adjacent_layers_compactness_explanation(
                    p=p,
                    layer1=layer1,
                    target_binary=target_binary,
                    alpha=alpha,
                    beta=beta,
                    rotation_deg=rotation_deg,
                    figsize=figsize,
                    save_path=save_path,
                    dpi=dpi,
                )

                print(
                    f"Rendered for p={p}, layers=(R{layer1}, R{layer2}), target={target_binary}"
                )
                if save_path:
                    print(f"Saved to: {save_path}")

            except Exception as e:
                print("Error:", e)

    p_dropdown.observe(update_layer_options, names="value")
    layer1_dropdown.observe(on_layer1_change, names="value")
    render_btn.on_click(on_render_click)

    update_layer_options()

    controls_left = widgets.VBox([
        p_dropdown,
        layer1_dropdown,
        layer2_text,
        target_text,
        dpi_dropdown,
    ])

    controls_mid = widgets.VBox([
        alpha_slider,
        beta_slider,
        rotation_slider,
    ])

    controls_right = widgets.VBox([
        figsize_width,
        figsize_height,
        save_path_text,
    ])

    ui = widgets.VBox([
        widgets.HTML("<h3>Pascalgonic Adjacent-Layer Explanatory Figure</h3>"),
        info_html,
        widgets.HBox([controls_left, controls_mid, controls_right]),
        render_btn,
        out,
    ])

    display(ui)


# ============================================================
# RUN UI
# ============================================================

build_pascalgonic_adjacent_layers_ui()
